properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  image.WordPress.fullReference:
    type: string
    default: docker.io/bitnami/wordpress:4.9.5
    x-google-marketplace:
      type: IMAGE
  mariadb.image:
    type: string
    default: docker.io/bitnami/mariadb:10.1.29-r1
    x-google-marketplace:
      type: IMAGE
required:
- name
- namespace
- image.WordPress.fullReference
- mariadb.image
