properties:
  APP_INSTANCE_NAME:
    type: string
    x-google-marketplace:
      type: NAME
  NAMESPACE:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  image.WordPress.fullReference:
    type: string
    default: docker.io/bitnami/wordpress:4.9.5
    x-google-marketplace:
      type: IMAGE
  image.MariaDB.fullReference:
    type: string
    default: docker.io/bitnami/mariadb:10.2.14
    x-google-marketplace:
      type: IMAGE
required:
- APP_INSTANCE_NAME
- NAMESPACE
- image.WordPress.fullReference
- image.MariaDB.fullReference
