steps:

- id: Fetch service account key
  name: gcr.io/cloud-builders/gsutil
  args:
  - cp
  - gs://cloud-marketplace-ops-test-kokoro/application_credentials
  - /builder/home/service_account.json

- id: Fetch key for the github app
  name: gcr.io/cloud-builders/gsutil
  args:
  - cp
  - gs://cloud-marketplace-ops-test-kokoro/appkeys/cloudbuild
  - cloudbuild.pem

- id: Set commit as pending
  waitFor:
  - Fetch key for the github app
  name: gcr.io/$PROJECT_ID/verifier
  entrypoint: bash
  args:
  - -c
  - |
    cloudbuild/set_commit_status.sh \
      --secret=cloudbuild.pem \
      --issuer=11572 \
      --state=pending \
      --target_url="https://pantheon.corp.google.com/gcr/builds/$BUILD_ID?project=$PROJECT_ID" \
      --description="Running integration tests" \
      --context="google-cloud/builder/integration-test" \
      --repo="$_REPO_NAME" \
      --commit=$COMMIT_SHA

- id: Fetch deploy keys for tools repo
  waitFor:
  - '-'
  name: gcr.io/cloud-builders/gsutil
  args:
  - cp
  - gs://cloud-marketplace-ops-test-kokoro/deploykeys/googlecloudplatform_marketplace-k8s-app-tools
  - /root/.ssh/googlecloudplatform_marketplace-k8s-app-tools
  volumes:
  - name: ssh
    path: /root/.ssh

- id: Fetch deploy keys for ubbagent repo
  waitFor:
  - '-'
  name: gcr.io/cloud-builders/gsutil
  args:
  - cp
  - gs://cloud-marketplace-ops-test-kokoro/deploykeys/googlecloudplatform_ubbagent
  - /root/.ssh/googlecloudplatform_ubbagent
  volumes:
  - name: ssh
    path: /root/.ssh

- id: Setup git repo
  waitFor:
  - Fetch deploy keys for tools repo
  - Fetch deploy keys for ubbagent repo
  name: gcr.io/cloud-builders/git
  entrypoint: bash
  args:
  - cloudbuild/fetch_submodules.sh
  volumes:
  - name: ssh
    path: /root/.ssh

- id: Authenticate
  name: gcr.io/cloud-marketplace-tools/k8s/dev:latest
  waitFor:
  - Fetch service account key
  volumes:
  - name: gcloud
    path: /root/.config/gcloud
  - name: kubectl
    path: /root/.kube
  args:
  - -e
  - -c
  - |
    gcloud auth activate-service-account --key-file="/builder/home/service_account.json"
    gcloud container clusters get-credentials "$_CLUSTER_NAME" --zone "$_CLUSTER_LOCATION"

- id: Build Wordpress
  name: gcr.io/cloud-marketplace-tools/k8s/dev:latest
  waitFor:
  - '-'
  dir: wordpress
  args:
  - -c
  - make clean app/build

- id: Verify Wordpress
  name: gcr.io/cloud-marketplace-tools/k8s/dev:latest
  waitFor:
  - Build Wordpress
  - Authenticate
  volumes:
  - name: gcloud
    path: /root/.config/gcloud
  - name: kubectl
    path: /root/.kube
  env:
  - APP_DEPLOYER=$_REGISTRY/example/wordpress/deployer:latest
  - |
    APP_PARAMETERS={
                     "name": "wordpress-1",
                     "namespace": "default",
                     "imageWordpress": "$_REGISTRY/example/wordpress:latest",
                     "imageInit": "$_REGISTRY/example/wordpress/init:latest",
                     "imageMysql": "$_REGISTRY/example/wordpress/mysql:latest",
                     "imageUbbagent": "$_REGISTRY/example/wordpress/ubbagent:latest",
                     "reportingSecret": "wordpress-1-reporting-secret",
                     "imageTester": "$_REGISTRY/example/wordpress/tester:latest"
                   }
  args:
  - -x
  - -c
  - |
    /scripts/driver_internal.sh \
        --deployer="$$APP_DEPLOYER" \
        --parameters="$$APP_PARAMETERS"

- id: Build NGINX
  name: gcr.io/cloud-marketplace-tools/k8s/dev:latest
  waitFor:
  - '-'
  dir: nginx
  args:
  - -c
  - make clean app/build

- id: Verify NGINX
  name: gcr.io/cloud-marketplace-tools/k8s/dev:latest
  waitFor:
  - Build NGINX
  - Authenticate
  volumes:
  - name: gcloud
    path: /root/.config/gcloud
  - name: kubectl
    path: /root/.kube
  env:
  - APP_DEPLOYER=$_REGISTRY/example/nginx/deployer:latest
  - |
    APP_PARAMETERS={
                     "name": "nginx-1",
                     "namespace": "default",
                     "imageNginx.image": "$_REGISTRY/example/nginx:latest",
                     "tester.image": "$_REGISTRY/example/nginx/tester:latest"
                   }
  args:
  - -x
  - -c
  - |
    /scripts/driver_internal.sh \
        --deployer="$$APP_DEPLOYER"
        --parameters="$$APP_PARAMETERS"

- id: Set commit as succeeded
  name: gcr.io/$PROJECT_ID/verifier
  waitFor:
  - Verify Wordpress
  - Verify NGINX
  entrypoint: bash
  args:
  - -c
  - |
    cloudbuild/set_commit_status.sh \
      --secret=cloudbuild.pem \
      --issuer=11572 \
      --state=success \
      --target_url="https://pantheon.corp.google.com/gcr/builds/$BUILD_ID?project=$PROJECT_ID" \
      --description="Integration tests passed." \
      --context="google-cloud/builder/integration-test" \
      --repo="$_REPO_NAME" \
      --commit=$COMMIT_SHA
