# Example Usage:
#
# $ gcloud container builds submit \
#     --config cloudbuild/local-cloudbuild.yaml \
#     --substitutions=_CLUSTER_LOCATION=<zone>,_CLUSTER_NAME=<cluster>,_REGISTRY=<registry> \
#     .
#
# $ container-builder-local \
#     --config cloudbuild/local-cloudbuild.yaml \
#     --substitutions=_CLUSTER_LOCATION=<zone>,_CLUSTER_NAME=<cluster>,_REGISTRY=<registry> \
#     --dryrun=false \
#     .
steps:

- id: Fetch service account key
  name: gcr.io/cloud-builders/gsutil
  waitFor:
  - '-'
  args:
  - cp
  - gs://cloud-marketplace-ops-test-kokoro/cloud-marketplace-ops-test-5cb3e979a3ae.json
  - /builder/home/service_account.json

- id: Authenticate
  name: gcr.io/cloud-marketplace-tools/k8s/dev:latest
  waitFor:
  - Fetch service account key
  volumes:
  - name: gcloud
    path: /root/.config/gcloud
  - name: kubectl
    path: /root/builder/.kube
  args:
  - -e
  - -c
  - |
    gcloud auth activate-service-account --key-file="/builder/home/service_account.json"
    CLOUDSDK_API_ENDPOINT_OVERRIDES_CONTAINER=https://staging-container.sandbox.googleapis.com/ gcloud container clusters get-credentials "$_CLUSTER_NAME" --zone "$_CLUSTER_LOCATION"

- id: Build Wordpress
  name: gcr.io/cloud-marketplace-tools/k8s/dev:latest
  waitFor:
  - '-'
  dir: wordpress
  args:
  - -c
  - make clean app/build

- id: Verify Wordpress
  name: gcr.io/cloud-marketplace-tools/k8s/dev:latest
  waitFor:
  - Build Wordpress
  - Authenticate
  volumes:
  - name: gcloud
    path: /root/.config/gcloud
  - name: kubectl
    path: /root/builder/.kube
  env:
  - APP_DEPLOYER=$_REGISTRY/example/wordpress/deployer:latest
  - |
    APP_PARAMETERS={
                     "name": "wordpress-1",
                     "namespace": "default",
                     "imageWordpress": "$_REGISTRY/example/wordpress:latest",
                     "imageInit": "$_REGISTRY/example/wordpress/init:latest",
                     "imageMysql": "$_REGISTRY/example/wordpress/mysql:latest",
                     "imageUbbagent": "$_REGISTRY/example/wordpress/ubbagent:latest",
                     "reportingSecret": "wordpress-1-reporting-secret",
                     "imageTester": "$_REGISTRY/example/wordpress/tester:latest"
                   }
  args:
  - -c
  - |
    /scripts/driver_internal.sh \
        --deployer="$$APP_DEPLOYER" \
        --parameters="$$APP_PARAMETERS"

- id: Build NGINX
  name: gcr.io/cloud-marketplace-tools/k8s/dev:latest
  waitFor:
  - '-'
  dir: nginx
  args:
  - -c
  - make clean app/build

- id: Verify NGINX
  name: gcr.io/cloud-marketplace-tools/k8s/dev:latest
  waitFor:
  - Build NGINX
  - Authenticate
  volumes:
  - name: gcloud
    path: /root/.config/gcloud
  - name: kubectl
    path: /root/builder/.kube
  env:
  - APP_DEPLOYER=$_REGISTRY/example/nginx/deployer:latest
  - |
    APP_PARAMETERS={
                     "imageNginx.image": "$_REGISTRY/example/nginx:latest",
                     "tester.image": "$_REGISTRY/example/nginx/tester:latest"
                   }
  args:
  - -c
  - |
    /scripts/driver_internal.sh \
        --deployer="$$APP_DEPLOYER" \
        --parameters="$$APP_PARAMETERS"
