steps:

- id: Get Kubernetes Credentials
  name: gcr.io/cloud-builders/gcloud
  args:
  - container
  - clusters
  - get-credentials
  - "limani-integ"
  - --region
  - "us-central1"
  - --project
  - "$PROJECT_ID"

- id: Initialized
  name: gcr.io/cloud-builders/docker
  entrypoint: /bin/bash
  waitFor:
  - Get Kubernetes Credentials
  args:
  - -exc
  - |
    find
    find /builder/home/.kube
    cp -r /builder/home/.kube /kube/
    find /builder/home/.config
    cp -r /builder/home/.config /config/
    docker run \
        --volume "/var/run/docker.sock:/var/run/docker.sock:ro" \
        --volume "/kube:/kube:ro" \
        --volume "/config:/config:ro" \
        --volume "/workspace/:/workspace/:ro" \
        --rm \
        --entrypoint=bash \
        gcr.io/cloud-builders/docker \
        -exc \
        -- \
        "find /kube/ ; find /config ; find /workspace/"
