steps:

- id: Fetch Service Account Key File
  name: gcr.io/cloud-builders/gsutil
  env:
  - MARKETPLACE_TOOLS_TAG=latest
  args:
  - cp
  - gs://cloud-marketplace-ops-test-kokoro/cloud-marketplace-ops-test-5cb3e979a3ae.json
  - cloud-marketplace-ops-test-5cb3e979a3ae.json

- id: Authenticate as Service Account
  name: gcr.io/cloud-builders/gcloud
  waitFor:
  - Fetch Service Account Key File
  args:
  - auth
  - activate-service-account
  - --key-file
  - cloud-marketplace-ops-test-5cb3e979a3ae.json

- id: Get Kubernetes Credentials
  name: gcr.io/cloud-builders/gcloud
  args:
  - container
  - clusters
  - get-credentials
  - "limani-integ"
  - --region
  - "us-central1"
  - --project
  - "$PROJECT_ID"

- id: Initialized
  name: gcr.io/cloud-builders/docker
  entrypoint: /bin/bash
  waitFor:
  - Get Kubernetes Credentials
  - Authenticate as Service Account
  args:
  - -exc
  - |
    cp -r /builder/home/.kube kube/
    cp -r /builder/home/.config config/
    chmod 666 -R kube
    chmod 666 -R config
    ls -Rla kube
    ls -Rla config
    ls -Rla wordpress
    docker run \
        --volume "/workspace/kube:/root/mount/.kube:ro" \
        --volume "/workspace/config:/root/mount/.config:ro" \
        --volume "/workspace/wordpress:/wordpress:ro" \
        --rm \
        --entrypoint=bash \
        gcr.io/cloud-marketplace-tools/k8s/dev:latest \
        -exc \
        -- \
        "source setup_kubeconfig.sh ;  kubectl get namespace"
