steps:

- id: Get Kubernetes Credentials
  name: gcr.io/cloud-builders/gcloud
  args:
  - container
  - clusters
  - get-credentials
  - "limani-integ"
  - --region
  - "us-central1"
  - --project
  - "$PROJECT_ID"

- id: Initialized
  name: gcr.io/cloud-builders/docker
  entrypoint: /bin/bash
  waitFor:
  - Get Kubernetes Credentials
  args:
  - -exc
  - |
    cp -r /builder/home/.kube kube/
    cp -r /builder/home/.config config/
    chmod 666 -R kube
    chmod 666 -R config
    ls -Rla kube
    ls -Rla config
    ls -Rla wordpress
    docker run \
        --volume "/workspace/kube:/root/mount/.kube:ro" \
        --volume "/workspace/config:/root/mount/.config:ro" \
        --volume "/workspace/wordpress:/wordpress:ro" \
        --rm \
        --entrypoint=bash \
        gcr.io/cloud-marketplace-tools/k8s/dev:latest \
        -exc \
        -- \
        "source setup_kubeconfig.sh ;  kubectl get namespace"
