steps:

- id: Get Kubernetes Credentials
  name: gcr.io/cloud-builders/gcloud
  args:
  - container
  - clusters
  - get-credentials
  - "limani-integ"
  - --region
  - "us-central1"
  - --project
  - "$PROJECT_ID"

- id: Initialized
  name: gcr.io/cloud-builders/docker
  entrypoint: /bin/bash
  waitFor:
  - Get Kubernetes Credentials
  args:
  - -exc
  - |
    cp -r /builder/home/.kube kube/
    find kube
    cp -r /builder/home/.config config/
    find config
    find wordpress
    docker run \
        --volume "kube:/kube:ro" \
        --volume "config:/config:ro" \
        --volume "wordpress:/wordpress:ro" \
        --rm \
        --entrypoint=bash \
        gcr.io/cloud-builders/docker \
        -exc \
        -- \
        "find /kube/ ; find /config/ ; find /wordpress/"
