steps:

- id: Get Kubernetes Credentials
  name: gcr.io/cloud-builders/gcloud
  args:
  - container
  - clusters
  - get-credentials
  - "limani-integ"
  - --region
  - "us-central1"
  - --project
  - "$PROJECT_ID"

- id: Initialized
  name: gcr.io/cloud-builders/docker
  entrypoint: /bin/bash
  waitFor:
  - Get Kubernetes Credentials
  args:
  - -exc
  - |
    cp -r /builder/home/.kube $$HOME/kube/
    ls -la $$HOME/kube
    cp -r /builder/home/.config $$HOME/config/
    ls -la $$HOME/config
    find wordpress
    docker run \
        --volume "$$HOME/kube:/kube:ro" \
        --volume "$$HOME/config:/config:ro" \
        --volume "/workspace/wordpress:/wordpress:ro" \
        --rm \
        --entrypoint=bash \
        gcr.io/cloud-builders/docker \
        -exc \
        -- \
        "find /kube/ ; find /config/ ; find /wordpress/"
