options:
 machineType: 'N1_HIGHCPU_8'

steps:

- id: Get Kubernetes Credentials
  name: gcr.io/cloud-builders/gcloud
  args:
  - container
  - clusters
  - get-credentials
  - cluster-1
  - --region
  - us-west1-a
  - --project
  - $PROJECT_ID
  waitFor:
  - '-'

- id: Pull cloud-marketplace-tools deployer_envsubst Image
  name: gcr.io/cloud-builders/docker
  entrypoint: /bin/bash
  args:
  - -exc
  - |
    MARKETPLACE_TOOLS_TAG=sha_52378efdad5b9da6885f37ae53959c73464c4ffd

    docker pull gcr.io/cloud-marketplace-tools/k8s/deployer_envsubst:$$MARKETPLACE_TOOLS_TAG
    docker tag gcr.io/cloud-marketplace-tools/k8s/deployer_envsubst:$$MARKETPLACE_TOOLS_TAG \
        gcr.io/cloud-marketplace-tools/k8s/deployer_envsubst:local
  waitFor:
  - '-'

- id: Pull cloud-marketplace-tools dev Image
  name: gcr.io/cloud-builders/docker
  entrypoint: /bin/bash
  args:
  - -exc
  - |
    MARKETPLACE_TOOLS_TAG=sha_52378efdad5b9da6885f37ae53959c73464c4ffd

    docker pull gcr.io/cloud-marketplace-tools/k8s/dev:$$MARKETPLACE_TOOLS_TAG
    docker tag gcr.io/cloud-marketplace-tools/k8s/dev:$$MARKETPLACE_TOOLS_TAG \
        gcr.io/cloud-marketplace-tools/k8s/dev:local
  waitFor:
  - '-'

#############
# Wordpress #
#############

- id: Build Wordpress Deployer
  name: gcr.io/cloud-builders/docker
  dir: wordpress
  entrypoint: deployer/build
  args:
  - --project_id=$PROJECT_ID
  - --tag=$BUILD_ID
  waitFor:
  - Pull cloud-marketplace-tools deployer_envsubst Image

- id: Build Wordpress Tester
  name: gcr.io/cloud-builders/docker
  dir: wordpress
  entrypoint: tester/build
  args:
  - --project_id=$PROJECT_ID
  - --tag=$BUILD_ID
  waitFor:
  - '-'

- id: Build Wordpress Image
  name: gcr.io/cloud-builders/docker
  dir: wordpress
  entrypoint: wordpress/build
  args:
  - --project_id=$PROJECT_ID
  - --tag=$BUILD_ID
  waitFor:
  - '-'

- id: Build Wordpress Init
  name: gcr.io/cloud-builders/docker
  dir: wordpress
  entrypoint: init/build
  args:
  - --project_id=$PROJECT_ID
  - --tag=$BUILD_ID
  waitFor:
  - '-'

- id: Build Wordpress Mysql
  name: gcr.io/cloud-builders/docker
  dir: wordpress
  entrypoint: init/build
  args:
  - --project_id=$PROJECT_ID
  - --tag=$BUILD_ID
  waitFor:
  - '-'

# TODO: Replace with wellknown ubbagent image, once available.
- id: Build Wordpress Ubbagent
  name: gcr.io/cloud-builders/docker
  dir: vendor/marketplace-tools/vendor/ubbagent
  args:
  - build
  - --tag
  - gcr.io/$PROJECT_ID/example/wordpress/ubbagent:local
  - .
  waitFor:
  - '-'

- id: Fetch Wordpress Reporting Secret
  name: gcr.io/cloud-builders/gsutil
  args:
  - cp
  - gs://cloud-marketplace-ops-test-kokoro/reporting_secrets/wordpress.yaml
  - reporting-secret.json
  waitFor:
  - '-'

- id: Verify Wordpress
  name: gcr.io/cloud-marketplace-tools/k8s/dev:local
  env:
  - APP_DEPLOYER=gcr.io/$PROJECT_ID/example/wordpress/deployer:local
  - |
    APP_PARAMETERS={
                     "reportingSecret": "file://reporting-secret.json",
                     "imageTester": "gcr.io/$PROJECT_ID/example/wordpress/tester:local"
                   }
  args:
  - -exc
  - |
    /scripts/driver_internal.sh \
        --deployer="$$APP_DEPLOYER" \
        --parameters="$$APP_PARAMETERS"
  waitFor:
  - Pull cloud-marketplace-tools dev Image
  - Get Kubernetes Credentials
  - Build Wordpress Deployer
  - Build Wordpress Tester
  - Build Wordpress Image
  - Build Wordpress Init
  - Build Wordpress Mysql
  - Build Wordpress Ubbagent
  - Fetch Wordpress Reporting Secret

- id: Publish Wordpress
  name: gcr.io/cloud-builders/docker
  entrypoint: /bin/bash
  args:
  - -exc
  - |
    [[ -z "$COMMIT_SHA" ]] && exit 0
    [[ -z "$SHORT_SHA" ]] && exit 0

    docker tag gcr.io/$PROJECT_ID/example/wordpress/deployer:$BUILD_ID \
               gcr.io/$PROJECT_ID/example/wordpress/deployer:sha_$COMMIT_SHA
    docker push gcr.io/$PROJECT_ID/example/wordpress/deployer:sha_$COMMIT_SHA

    docker tag gcr.io/$PROJECT_ID/example/wordpress/deployer:$BUILD_ID \
               gcr.io/$PROJECT_ID/example/wordpress/deployer:sha_$SHORT_SHA
    docker push gcr.io/$PROJECT_ID/example/wordpress/deployer:sha_$SHORT_SHA

    docker tag gcr.io/$PROJECT_ID/example/wordpress/tester:$BUILD_ID \
               gcr.io/$PROJECT_ID/example/wordpress/tester:sha_$COMMIT_SHA
    docker push gcr.io/$PROJECT_ID/example/wordpress/tester:sha_$COMMIT_SHA

    docker tag gcr.io/$PROJECT_ID/example/wordpress/tester:$BUILD_ID \
               gcr.io/$PROJECT_ID/example/wordpress/tester:sha_$SHORT_SHA
    docker push gcr.io/$PROJECT_ID/example/wordpress/tester:sha_$SHORT_SHA

    docker tag gcr.io/$PROJECT_ID/example/wordpress:$BUILD_ID \
               gcr.io/$PROJECT_ID/example/wordpress:sha_$COMMIT_SHA
    docker push gcr.io/$PROJECT_ID/example/wordpress:sha_$COMMIT_SHA

    docker tag gcr.io/$PROJECT_ID/example/wordpress:$BUILD_ID \
               gcr.io/$PROJECT_ID/example/wordpress:sha_$SHORT_SHA
    docker push gcr.io/$PROJECT_ID/example/wordpress:sha_$SHORT_SHA

    docker tag gcr.io/$PROJECT_ID/example/wordpress/init:$BUILD_ID \
               gcr.io/$PROJECT_ID/example/wordpress/init:sha_$COMMIT_SHA
    docker push gcr.io/$PROJECT_ID/example/wordpress/init:sha_$COMMIT_SHA

    docker tag gcr.io/$PROJECT_ID/example/wordpress/init:$BUILD_ID \
               gcr.io/$PROJECT_ID/example/wordpress/init:sha_$SHORT_SHA
    docker push gcr.io/$PROJECT_ID/example/wordpress/init:sha_$SHORT_SHA

    docker tag gcr.io/$PROJECT_ID/example/wordpress/mysql:$BUILD_ID \
               gcr.io/$PROJECT_ID/example/wordpress/mysql:sha_$COMMIT_SHA
    docker push gcr.io/$PROJECT_ID/example/wordpress/mysql:sha_$COMMIT_SHA

    docker tag gcr.io/$PROJECT_ID/example/wordpress/mysql:$BUILD_ID \
               gcr.io/$PROJECT_ID/example/wordpress/mysql:sha_$SHORT_SHA
    docker push gcr.io/$PROJECT_ID/example/wordpress/mysql:sha_$SHORT_SHA

    docker tag gcr.io/$PROJECT_ID/example/wordpress/ubbagent:$BUILD_ID \
               gcr.io/$PROJECT_ID/example/wordpress/ubbagent:sha_$COMMIT_SHA
    docker push gcr.io/$PROJECT_ID/example/wordpress/ubbagent:sha_$COMMIT_SHA

    docker tag gcr.io/$PROJECT_ID/example/wordpress/ubbagent:$BUILD_ID \
               gcr.io/$PROJECT_ID/example/wordpress/ubbagent:sha_$SHORT_SHA
    docker push gcr.io/$PROJECT_ID/example/wordpress/ubbagent:sha_$SHORT_SHA
  waitFor:
  - Verify Wordpress

# ######################
# # NGINX Verification #
# ######################
# 
# - id: Verify NGINX
#   name: gcr.io/cloud-marketplace-tools/k8s/dev:sha_8f95946d0f7df2bdaad674a226e73df4aceeccc1
#   waitFor:
#   - Get Kubernetes Credentials
#   dir: nginx
#   args:
#   - -exc
#   - make -j4 clean app/verify
