steps:

- id: Get Kubernetes Credentials
  name: gcr.io/cloud-builders/gcloud
  args:
  - container
  - clusters
  - get-credentials
  - "limani-integ"
  - --region
  - "us-central1"
  - --project
  - "$PROJECT_ID"

- id: Initialized
  name: gcr.io/cloud-builders/docker
  entrypoint: /bin/bash
  waitFor:
  - Get Kubernetes Credentials
  args:
  - -exc
  - |
    find
    find /builder/home/.kube
    find /builder/home/.config
    docker --version
    docker run \
        --volume "/var/run/docker.sock:/var/run/docker.sock:ro" \
        --volume "/builder/home/.kube:/root/mount2/.kube:ro" \
        --volume "/builder/home/.config:/root/mount2/.config:ro" \
        --volume "/workspace/:/workspace/:ro" \
        --rm \
        --entrypoint=bash \
        gcr.io/cloud-builders/docker \
        -exc \
        -- \
        "find /root/mount2/ ; find /workspace/"
