apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-controller-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/component: controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-controller-rb
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/component: controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-controller-sa
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-controller
  labels: &ControllerLabels
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/component: controller
    app: {{ template "nginx.name" . }}
    chart: {{ template "nginx.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: controller
spec:
  replicas: 1
  selector:
    matchLabels: *ControllerLabels
  template:
    metadata:
      labels: *ControllerLabels
    spec:
      serviceAccountName: {{ .Release.Name }}-controller-sa
      containers:
      - name: controller
        image: {{ .Values.imageController.image }}:{{ .Values.imageController.tag }}
        imagePullPolicy: {{ .Values.imageController.pullPolicy }}
        env:
        - name: APP_INSTANCE_NAME
          value: "{{ .Release.Name }}"
        - name: NAMESPACE
          value: "{{ .Release.Namespace }}"
